apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tmh.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tmh.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Release.db_host | quote }}
  DB_PORT: {{ .Release.db_port | quote }}
  DB_USER: {{ .Release.db_user | quote }}
  DB_PASSWORD: {{ .Release.db_password | quote }}
  DB_NAME: {{ .Release.db_name | quote }}